### ISSUE TITLE
":" as database path separator is inconvenient for Windows users

### ISSUE THREAD

**Issue by Jakob-Bach** [Udopia/gbd#15]
Currently, the colon is used in `GbdApi.__init__()` to split the `db_string`. This results in wrong splits for absolute paths on Windows systems, e.g., `C:/data/test.db` is split into two database paths, `C` and `/data/test.db`.

**Comment by Udopia** [comment]
Thank you for the feedback! I just fixed it by switching to semi-colon for Windows, and leaving the colon only for other systems
