### ISSUE TITLE
-t parameter not recognized

### ISSUE THREAD

**Issue by SimuIacron** [Udopia/gbd#17]
When executing the command  "gbd eval par2 "competition_track = main_2020" -t 5000 -r kissat_sat relaxed_newtech" (copied from the "Collaborative Management of Benchmark Instances and their Attributes" PDF). The following error occurs:

`usage: gbd [-h] [-d [DB]] [-j [JOBS]] [-t TIMEOUT] [-s { ,,,;}] [--join-type {INNER,OUTER,LEFT}] [-v]
           {init,hash,get,set,import,create,delete,rename,info,info_set,info_clear,eval,plot,graph} ...
gbd: error: unrecognized arguments: -t 5000`

Removing the "-t 5000" from the command the terminal returns the expected result:

`3926.19 264/400 kissat_sat
4140.31 255/400 relaxed_newtech
3323.5 285/400 VBS`

This issue could be reproduced on Linux Mint 20 Cinnamon (4.6.7), a Virtual Machine running Linux Mint 20.2 Cinnamon (5.0.4) and a Windows Subsystem running Ubuntu 20.04 LTS

**Comment by Udopia** [comment]
-t is a global argument, but you put it local to eval. You need to reposition it, then it works:

gbd -t 5000 eval par2 "track = main_2020" -r kissat_sat relaxed_newtech
