### ISSUE TITLE
Import Error for gbd eval comb

### ISSUE THREAD

**Issue by SimuIacron** [Udopia/gbd#18]
When using the command "gbd eval comb "competition_track = main_2020" -k 3 -r cadical_sc2020 kissat exmaple_padc_dl ... | sort" (note: removed -t 5000, because of #17 ) the follwing error occurs:

`Traceback (most recent call last):
  File "/home/u1/.local/bin/gbd", line 8, in <module>
    sys.exit(main())
  File "/home/u1/.local/bin/gbd.py", line 315, in main
    args.func(api, args)
  File "/home/u1/.local/bin/gbd.py", line 103, in cli_eval_combinations
    from gbd_tool import eval_comp_ilp as eci
ImportError: cannot import name 'eval_comp_ilp' from 'gbd_tool' (/home/u1/.local/lib/python3.8/site-packages/gbd_tool/__init__.py)`

This issue could be reproduced on Linux Mint 20 Cinnamon (4.6.7), a Virtual Machine running Linux Mint 20.2 Cinnamon (5.0.4) and a Windows Subsystem running Ubuntu 20.04 LTS

**Comment by Udopia** [comment]
Fixed
