### ISSUE TITLE
`get_features()` only returns feature names of one database

### ISSUE THREAD

**Issue by Jakob-Bach** [Udopia/gbd#19]
... if called with `dbname=None` (the default), but `gbd_tool.gbd_api.GBD()` initialized with a string representing multiple databases (separated by `:`).

**Comment by Udopia** [comment]
Thanks, need to analyze.. wanted to pull out string and separators anyways (belongs to cli)

**Comment by Udopia** [comment]
Hi Jakob, 
I cannot reproduce this in gbd-tools 3.8.0; The following code works as expected:

`from gbd_tool.gbd_api import GBD
import os

dir = "/home/iser/git/gbd-data/"
dbs = ["meta.db", "base.db", "gate.db", "runtimes.db"]
with GBD(os.pathsep.join([dir + db for db in dbs])) as gbd:
    print(gbd.get_features(dbname="base_db"))
    print(gbd.get_features(dbname="gate_db"))
    print(gbd.get_features(dbname="runtimes_db"))
    print(gbd.get_features(dbname=None))`

Note that soon (from upcoming version 3.8.1), the first argument to GBDs constructor will be a list and not an os.pathsep - separated string.

**Comment by Jakob-Bach** [comment]
Sorry, my mistake, I wasn't aware that the separator needs to be `os.pathsep` (on Windows, that's not `:`, but `;`; with the latter, the code works on my machine as well).
